# Generated by Django 3.2.15 on 2022-10-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('online', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Online')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=512, verbose_name='Content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Send AT')),
                ('read', models.BooleanField(default=False, verbose_name='Message Read')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation', verbose_name='Conversation')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from_me', to=settings.AUTH_USER_MODEL, verbose_name='Message By')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to_me', to=settings.AUTH_USER_MODEL, verbose_name='Message To')),
            ],
        ),
    ]
